pizzeria/pizzas/urls.py
from django.urls import path
from . import views


app_name = 'pizzas'
urlpatterns = [
    # Домашняя страница с видами пиццы
    path('', views.index, name='index'),
    # Страница с добавками для пиццы
    path('<int:pizza_id>/', views.pizza_toping, name='pizza_toping'),

]

pizzeria/pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

pizzeria/pizzas/models.py
from django.db import models

class Pizza(models.Model):
    """таблица видов пиццы"""
    name = models.CharField(max_length=100)  # название пиццы

    def __str__(self):  # описание таблицы
        return self.name


class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)  # название добавки

    def __str__(self):  # описание таблицы
        return self.name

pizzeria/pizzas/views.py
from django.shortcuts import render
from .models import Pizza, Topping

def index(request):
    pizza_types_info = Pizza.objects.all()
    pizza_types_context = {'pizzas': pizza_types_info}
    return render(request, 'pizzas/main_pizzas.html', pizza_types_context)

def pizza_toping(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.all()

    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza_toping.html', context)

pizzeria/pizzas/templates/pizzas/base.html
<p>
    <h1>ПИЦЦЕРИЯ</h1>
    <br>

    <h2><a href="{% url 'pizzas:index' %}">Виды пиццы</a>
    </h2>
            </p>

<br>
{% block content %}{% endblock content %}

pizzeria/pizzas/templates/pizzas/main_pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}
                <ul>
                    {% for pizza in pizzas %}
                       <li>
                           <a href="{% url 'pizzas:pizza_toping' pizza.id %}">{{ pizza }}</a>
                       </li>
                       {% empty %}
                            <li>К сожалению сейчас пиццы нет....</li>
                       {% endfor %}
                   </ul>
            {% endblock content %}

pizzeria/pizzas/templates/pizzas/pizza_toping.html
{% extends "pizzas/base.html" %}

{% block content %}
    <p>{{ pizza }} может быть дополнена следующими ингридиентами:</p>

                <ul>
                    {% for topping in toppings %}
                       <li>{{ topping }}</li>
                       {% empty %}
                            <li>К сожалению для этой пиццы у нас нет дополнений....</li>
                       {% endfor %}
                   </ul>
            {% endblock content %}